name: checkbox-myproject 
summary: Checkbox tests for Snappy devices
description: "The provider is a collection of tests to be run on Snappy devices.\n"
version: 'V0.1'
grade: stable

base: core18

# Don't forget to add a new slot if a new provider part is added in the parts
# section below.
slots:
  provider-resource:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-resource
  provider-checkbox:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-checkbox
  provider-snappy:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-snappy
  provider-ipdt:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-ipdt
  provider-docker:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-docker
  provider-tpm2:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-tpm2
  provider-engineering-tests:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-engineering-tests
  provider-sru:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-sru
  provider-edgex:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-edgex
  checkbox-runtime:
    interface: content
    read:
      - /

apps:
  myproject-test-runner:
    command: bin/myproject-test-runner

parts:
  fwts:
    source-tag: ""
    source-type: "git"
    source: "https://git.launchpad.net/fwts"
  stress-ng:
    source-tag: ""
    source-type: "git"
    source: "https://git.launchpad.net/stress-ng"
    after: [plainbox-provider-checkbox]
  checkbox-support-dev:
    source-tag: ""
    source: "https://git.launchpad.net/checkbox-support"
    after: [fwts]
  checkbox-ng-dev:
    source-tag: ""
    source: "https://git.launchpad.net/checkbox-ng"
  plainbox-provider-resource:
    source-tag: ""
    source: "https://git.launchpad.net/plainbox-provider-resource"
    after: [checkbox-support-dev, checkbox-ng-dev]
  plainbox-provider-checkbox:
    source-tag: ""
    source: "https://git.launchpad.net/plainbox-provider-checkbox"
    stage:
      - -usr/bin/stress-ng
      - -usr/share/man/man1/stress-ng*
      - -usr/share/stress-ng/*
    after: [plainbox-provider-resource]
  plainbox-provider-snappy:
    source-tag: ""
    source: "https://git.launchpad.net/plainbox-provider-snappy"
    stage:
      - -usr/bin/stress-ng
      - -usr/share/man/man1/stress-ng*
      - -usr/share/stress-ng/*
    after: [plainbox-provider-checkbox]
  plainbox-provider-demo:
    plugin: plainbox-provider
    source-type: "local"
    source: "../plainbox-provider-myproject"
    after: [plainbox-provider-snappy]
  launchers:
    plugin: dump
    source: "../launchers"
    source-type: "local"
    organize:
      '*': bin/
